require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/jits", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Jit. As you add validations to Jit, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Jit.create! valid_attributes
      get jits_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      jit = Jit.create! valid_attributes
      get jit_url(jit)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_jit_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      jit = Jit.create! valid_attributes
      get edit_jit_url(jit)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Jit" do
        expect {
          post jits_url, params: { jit: valid_attributes }
        }.to change(Jit, :count).by(1)
      end

      it "redirects to the created jit" do
        post jits_url, params: { jit: valid_attributes }
        expect(response).to redirect_to(jit_url(Jit.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Jit" do
        expect {
          post jits_url, params: { jit: invalid_attributes }
        }.to change(Jit, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post jits_url, params: { jit: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested jit" do
        jit = Jit.create! valid_attributes
        patch jit_url(jit), params: { jit: new_attributes }
        jit.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the jit" do
        jit = Jit.create! valid_attributes
        patch jit_url(jit), params: { jit: new_attributes }
        jit.reload
        expect(response).to redirect_to(jit_url(jit))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        jit = Jit.create! valid_attributes
        patch jit_url(jit), params: { jit: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested jit" do
      jit = Jit.create! valid_attributes
      expect {
        delete jit_url(jit)
      }.to change(Jit, :count).by(-1)
    end

    it "redirects to the jits list" do
      jit = Jit.create! valid_attributes
      delete jit_url(jit)
      expect(response).to redirect_to(jits_url)
    end
  end
end
